// Constantes de permisos específicos para gestión de eventos
export const EVENT_PERMISSIONS = {
  // Permisos básicos de eventos
  VIEW_EVENTS: 'view_events',
  CREATE_EVENTS: 'create_events',
  UPDATE_EVENTS: 'update_events',
  DELETE_EVENTS: 'delete_events',

  // Permisos específicos de acciones sobre eventos
  PUBLISH_EVENTS: 'publish_events',
  CANCEL_EVENTS: 'cancel_events',
  DUPLICATE_EVENTS: 'duplicate_events',
  CHANGE_EVENT_STATUS: 'change_event_status',

  // Permisos de gestión avanzada
  MANAGE_EVENT_MEDIA: 'manage_event_media',
  VIEW_EVENT_REPORTS: 'view_event_reports',
  EXPORT_EVENT_DATA: 'export_event_data',
  MANAGE_EVENT_ANALYTICS: 'manage_event_analytics',

  // Permisos administrativos de eventos
  APPROVE_EVENTS: 'approve_events',
  ARCHIVE_EVENTS: 'archive_events',
  MANAGE_EVENT_CATEGORIES: 'manage_event_categories',
  MANAGE_EVENT_TYPES: 'manage_event_types',

  // Permisos de configuración
  CONFIGURE_EVENT_NOTIFICATIONS: 'configure_event_notifications',
  MANAGE_EVENT_TEMPLATES: 'manage_event_templates',
} as const;

// Tipos para los permisos de eventos
export type EventPermission = typeof EVENT_PERMISSIONS[keyof typeof EVENT_PERMISSIONS];

// Grupos de permisos por rol
export const EVENT_PERMISSION_GROUPS = {
  BASIC_MANAGER: [
    EVENT_PERMISSIONS.VIEW_EVENTS,
    EVENT_PERMISSIONS.CREATE_EVENTS,
    EVENT_PERMISSIONS.UPDATE_EVENTS,
    EVENT_PERMISSIONS.DUPLICATE_EVENTS,
    EVENT_PERMISSIONS.MANAGE_EVENT_MEDIA,
  ],

  ADVANCED_MANAGER: [
    EVENT_PERMISSIONS.VIEW_EVENTS,
    EVENT_PERMISSIONS.CREATE_EVENTS,
    EVENT_PERMISSIONS.UPDATE_EVENTS,
    EVENT_PERMISSIONS.DELETE_EVENTS,
    EVENT_PERMISSIONS.PUBLISH_EVENTS,
    EVENT_PERMISSIONS.CANCEL_EVENTS,
    EVENT_PERMISSIONS.CHANGE_EVENT_STATUS,
    EVENT_PERMISSIONS.DUPLICATE_EVENTS,
    EVENT_PERMISSIONS.MANAGE_EVENT_MEDIA,
    EVENT_PERMISSIONS.VIEW_EVENT_REPORTS,
    EVENT_PERMISSIONS.EXPORT_EVENT_DATA,
  ],

  ADMIN: [
    EVENT_PERMISSIONS.VIEW_EVENTS,
    EVENT_PERMISSIONS.CREATE_EVENTS,
    EVENT_PERMISSIONS.UPDATE_EVENTS,
    EVENT_PERMISSIONS.DELETE_EVENTS,
    EVENT_PERMISSIONS.PUBLISH_EVENTS,
    EVENT_PERMISSIONS.CANCEL_EVENTS,
    EVENT_PERMISSIONS.CHANGE_EVENT_STATUS,
    EVENT_PERMISSIONS.DUPLICATE_EVENTS,
    EVENT_PERMISSIONS.MANAGE_EVENT_MEDIA,
    EVENT_PERMISSIONS.VIEW_EVENT_REPORTS,
    EVENT_PERMISSIONS.EXPORT_EVENT_DATA,
    EVENT_PERMISSIONS.MANAGE_EVENT_ANALYTICS,
    EVENT_PERMISSIONS.APPROVE_EVENTS,
    EVENT_PERMISSIONS.ARCHIVE_EVENTS,
    EVENT_PERMISSIONS.MANAGE_EVENT_CATEGORIES,
    EVENT_PERMISSIONS.MANAGE_EVENT_TYPES,
    EVENT_PERMISSIONS.CONFIGURE_EVENT_NOTIFICATIONS,
    EVENT_PERMISSIONS.MANAGE_EVENT_TEMPLATES,
  ],

  SUPER_ADMIN: [
    // Todos los permisos
    ...Object.values(EVENT_PERMISSIONS),
  ],
} as const;